# Generated by Django 2.1.5 on 2019-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_auto_20190114_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='publisher_name',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fact',
            name='text',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
