# Generated by Django 2.1.5 on 2019-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_auto_20190114_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
